[package]
edition = "2018"
name = "packet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cipher = {path = "../cipher"}
miniz_oxide = "0.5.0"
serde = {version = "1.0.130", features = ["derive"]}
