[workspace]
members = [
    "proxy",
    "maion-core",
    "packet",
    "protocol",
    "plugin",
    "plugin-loader",
    "plugin-interface",
    "config-loader",
    "cipher",
    "plugins/test-plugin",
]

default-members = ["proxy"]