logging_packets:
  - Handshake
  - StatusResponse
  # - StatusPong
  - StatusRequest
  # - StatusPing
  - Disconnect
  - EncRequest
  - LoginSuccess
  # - SetCompression
  - PluginRequest
  - LoginStart
  - EncResponse
  - PluginResponse
  # - SpawnEntity
  # - SpawnXpOrb
  # - SpawnLivingEntity
  # - SpawnPainting
  # - SpawnPlayer
  # - AckPlayerDigging
  - ChatMessageClientbound
  # - TabCompleteClientbound
  # - ChatMessageServerbound
  - ResourcePackSend
  # - ClientSettings
  # - UpdateHealth
  # - PlayerPosition
  # - PlayerPositionRotation
  - PlayerAbilities
  # - KeepAliveCb
  # - KeepAliveSb
  - UpdateScore
  - DisplayScoreboard
  # - ScoreboardObjective
  # - Teams
  - ResourcePackStatus

player_uuid: f54c74dd3362422c80f9da71eca4aaa3
player_auth_token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTY0M2EzYmU0NGY4NmVlODE4OWEwMDllMGNlYTNmYSIsInlnZ3QiOiJmOTExOTk0M2E0ODI0OGQ3OWYyNDVlNDY5OWMyMWFhYSIsInNwciI6ImY1NGM3NGRkMzM2MjQyMmM4MGY5ZGE3MWVjYTRhYWEzIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MjI4MzQ4NjEsImlhdCI6MTYyMjY2MjA2MX0.tYFif4l7qA8d5GiBFgbZ77uEN6IjsbMgqJiACJ4Q5As
