logging_packets:
  - Handshake
  - StatusResponse
  # - StatusPong
  - StatusRequest
  # - StatusPing
  - Disconnect
  - EncRequest
  - LoginSuccess
  # - SetCompression
  - PluginRequest
  - LoginStart
  - EncResponse
  - PluginResponse
  # - SpawnEntity
  # - SpawnXpOrb
  # - SpawnLivingEntity
  # - SpawnPainting
  # - SpawnPlayer
  # - AckPlayerDigging
  - ChatMessageClientbound
  # - TabCompleteClientbound
  # - ChatMessageServerbound
  - ResourcePackSend
  # - ClientSettings
  # - UpdateHealth
  # - PlayerPosition
  # - PlayerPositionRotation
  - PlayerAbilities
  # - KeepAliveCb
  # - KeepAliveSb
  # - UpdateScore
  # - DisplayScoreboard
  # - ScoreboardObjective
  # - Teams
  - ResourcePackStatus

player_uuid: f54c74dd3362422c80f9dasadfsf71eca4aaa3
player_auth_token: easfsadfyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI2NTY0M2EzYmU0NGY4NmVlODE4OWEwMDllMGNlYTNmYSIsInlnZ3QiOiIzMGVhNTk4M2RhMWE0NGZhYjBiNzQ4N2Q2MThlZTA1OCIsInNwciI6ImY1NGM3NGRkMzM2MjQyMmM4MGY5ZGE3MWVjYTRhYWEzIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MjQ3MjMzNjIsImlhdCI6MTYyNDU1MDU2Mn0.NDRupxUdQIULfdD_gmUnWX_NPFZw0DprICfn_1c6nN4
ws_url: ws://127.0.0.1:8080
ws_enabled: true
